import { Box } from '@chakra-ui/react';
import Head from 'next/head';
import { Banner } from '../components/Banner';

import { Header } from '../components/Header';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box w='100vw' maxW={1480} mx='auto'>
        <Header />
        <Banner />
      </Box>
    </>
  )
}
