import { Box, Text, Flex } from '@chakra-ui/react';
import Head from 'next/head';

import { Banner } from '../components/Banner';
import { ContinentSlider } from '../components/ContinentSlider';
import { Header } from '../components/Header';
import { HomeDivider } from '../components/HomeDivider';
import { TravelTypes } from '../components/TravelTypes';

export default function Home() {
  return (
    <>
      <Head>
        <title>worldtrip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w='100vw' maxW={1480} mx='auto' display='flex' flexDir='column' alignItems='center'>
        <Header />

        <Banner />

        <TravelTypes />

        <HomeDivider />

        <Box display='flex' justifyContent='center' mb='3.25rem'>
          <Text fontWeight='500' fontSize='2.25rem' textAlign='center'>
            Vamos nessa? <br />
            Então escolha seu continente
          </Text>
        </Box>

        <ContinentSlider />
      </Flex>
    </>
  )
}
